---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /opt/volumes/nfs-server-volume
  persistentVolumeReclaimPolicy: Retain