---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
spec:
  storageClassName: ""
  volumeName: nfs-server-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi